# Generated by Django 2.2.1 on 2022-10-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='author_id',
            new_name='author_user_id',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='reviewer_id',
            new_name='reviewer_user_id',
        ),
        migrations.RenameField(
            model_name='reviewcomments',
            old_name='commenter_id',
            new_name='commenter_user_id',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='reviewer_id',
            new_name='reviewer_user_id',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_main.user_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.TextField(default=1, primary_key=True, serialize=False),
        ),
    ]
