# Generated by Django 2.2.1 on 2022-10-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221025_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.TextField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
