# Generated by Django 4.1.2 on 2022-10-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0004_auto_20221025_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='acceptance_state',
        ),
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Submitted'), (1, 'Submitted, but Pending'), (2, 'Submitted, and Rejected'), (3, 'Submitted, and Accepted')], default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewcomments',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='max_papers',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'System Admin'), (1, 'Conference Chair'), (2, 'Reviewer'), (3, 'Author')]),
        ),
    ]
