# Generated by Django 4.1.3 on 2022-11-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_paper_acceptance_state_paper_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomments',
            name='comment_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='author_rating',
            field=models.IntegerField(choices=[(-5, 'Unrated'), (-3, 'Strong Reject'), (-2, 'Reject'), (-1, 'Weak Reject'), (0, 'Borderline'), (1, 'Weak Accept'), (2, 'Accept'), (3, 'Strong Accept')], default=-5),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewer_rating',
            field=models.IntegerField(choices=[(-5, 'Unrated'), (-3, 'Strong Reject'), (-2, 'Reject'), (-1, 'Weak Reject'), (0, 'Borderline'), (1, 'Weak Accept'), (2, 'Accept'), (3, 'Strong Accept')], default=-5),
        ),
    ]
