# Generated by Django 4.1.3 on 2022-11-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_reviewcomments_comment_text_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Writes',
        ),
    ]
